

create table User (
	id BIGINT GENERATED by default as IDENTITY (START with 1, INCREMENT by 1) NOT NULL,
	email varchar(64),
	password varchar(64),
	firstName varchar(100),
	lastName varchar(100),
	student_id int,
	token int,
	primary key (id)
);

create table Activity (
	id BIGINT GENERATED by default as IDENTITY (START with 1, INCREMENT by 1) NOT NULL,
	activity_id int,
	title varchar(100),
	location varchar(100),
	seat int,
	startDate date,
	startTime time,
	status VARCHAR(10),
	primary key (id)
);

create table Bidding (
	id BIGINT GENERATED by default as IDENTITY (START with 1, INCREMENT by 1) NOT NULL,
	activity_id int,
	student_id int,
	token int,
	status VARCHAR(10),
	session_id varchar(500),
	ip_address varchar(50),
	browser varchar(20),
	version varchar(100),
	os varchar(100),
	primary key (id)
);

