
create table User (
	id BIGINT GENERATED by default as IDENTITY (START with 1, INCREMENT by 1) NOT NULL,
	email varchar(64),
	password varchar(64),
	firstName varchar(100),
	lastName varchar(100),
	student_id int,
	major varchar(100),
	faculty varchar(100),
	token int,
	role varchar(20),
	primary key (id)
);

create table Activity (
	id BIGINT GENERATED by default as IDENTITY (START with 1, INCREMENT by 1) NOT NULL,
	activity_name varchar(100),
	description varchar(500),
	place varchar(100),
	seat_quota int,
	start_time timestamp,
	end_time timestamp,
	isSelected boolean,
	primary key (id)
);

create table Bidding (
	id BIGINT GENERATED by default as IDENTITY (START with 1, INCREMENT by 1) NOT NULL,
	activity_id BIGINT,
	title varchar(100),
	description varchar(500),
	bStart_time timestamp,
	bEnd_time timestamp,
	seat_quota int,
	status varchar(10),
	primary key (id)
);


create table BidData (
	id BIGINT GENERATED by default as IDENTITY (START with 1, INCREMENT by 1) NOT NULL,
	bidding_id BIGINT,
	student_id int,
	firstName varchar(100),
	lastName varchar(100),
	token int,
	placeBidTime timestamp,
	status VARCHAR(10),
	session_id varchar(500),
	ip_address varchar(50),
	browser varchar(100),
	os varchar(100),
	primary key (id)
);

